"""Production `UpstreamDataSource` backed by `asyncua.Client`.

Design:
 - Each configured connection gets its own worker thread running an asyncio
   event loop. The `asyncua.Client` lives on that loop.
 - Every API-side call (`read_values`, `add_monitored_items`, ...) is bridged
   to the target thread via `ThreadPool.run_on`; results come back on the API
   loop.
 - After a successful connect, the binding runs an initial browse + type
   reflection and pushes the snapshot to the main-loop registries via
   `asyncio.run_coroutine_threadsafe`.

OPC UA-SIDE SUBSCRIPTIONS ARE MANDATORY.
We DO NOT poll the OPC UA server for value changes. Every i3X subscription
registration cascades to an asyncua `Subscription.subscribe_data_change(...)`
creating a real OPC UA MonitoredItem on the server. Server-side publishing
interval comes from `connections[*].subscriptions[*].publishing_interval_ms`;
sampling interval is forwarded per MonitoredItem so the server controls how
often it samples each node.

Samples flow: asyncua `datachange_notification(node, val, data)` (sync callback
on the connection thread) -> `_Handler.datachange_notification` -> task that
calls `_ConnectionBinding.deliver_sample` -> Part-6 encode via
`from_ua_data_value` + `sample_from_ouajson_data_value` -> cross-loop bridge to
the main loop's `SubscriptionManager.push` + `HistoryStore.append`.

Everything related to the live OPC UA wire lives here so `core/` and `api/`
remain framework-neutral.
"""

from __future__ import annotations

import asyncio
import logging
import tempfile
import time
from collections.abc import Iterable
from dataclasses import dataclass, replace
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from asyncua import ua
from asyncua.common.structures104 import load_enums
from asyncua.common.subscription import DataChangeNotif

# Placeholder namespace URI for DataTypes generated by asyncua's
# `load_data_type_definitions`; asyncua doesn't expose a direct NamespaceUri
# per generated class, so we reuse the connection-scoped fallback until we
# can map index -> URI at reconcile time.
from i3xua.adapters.asyncua.browse import (
    HAS_COMPONENT_REFS,
    RELATIONSHIP_NAMES,
    BrowseConfig,
    BrowsedChild,
    BrowseSource,
    InstanceDeclaration,
    NodeInfo,
    TypeInfo,
    browse,
)
from i3xua.adapters.asyncua.connection import AsyncuaConnection, UaClientLike
from i3xua.adapters.asyncua.convert import (
    from_ua_data_value,
)
from i3xua.adapters.asyncua.runtime import ThreadPool
from i3xua.adapters.asyncua.subscribe import sample_from_ouajson_data_value
from i3xua.adapters.asyncua.trust import resolve_server_cert
from i3xua.adapters.asyncua.typemap import (
    structure_to_json_schema_with_unresolved,
)
from i3xua.adapters.asyncua.uri_aware import (
    _UriAwareClient,
    pick_matching_endpoint,
)
from i3xua.core.history import HistoryStore
from i3xua.core.neutral import (
    BrowseResult,
    ConnectionId,
    ElementRef,
    NamespaceInfo,
    NodeClass,
    Quality,
    SubscriptionHandle,
    TypeDescriptor,
    ValueSample,
)
from i3xua.core.registry import (
    InstanceRegistry,
    NamespaceRegistry,
    RegisteredType,
    TypeRegistry,
    type_structural_hash,
)
from i3xua.core.subscriptions import SubscriptionManager
from i3xua.ouajson.types import DataValue as OUaDataValue
from i3xua.settings import AppConfig, ChannelNone, ChannelSigned, ConnectionConfig

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------- helpers

# Variable metadata batch: one multi-attr `Read` covering DataType plus the
# five attributes tag-heavy SCADA servers reliably populate. Order matters —
# `_decode_metadata_results` unwinds in the same (var-major, attr-minor)
# layout that `_build_metadata_read_items` produces.
_METADATA_ATTRS: tuple[Any, ...] = (
    ua.AttributeIds.DataType,
    ua.AttributeIds.ValueRank,
    ua.AttributeIds.ArrayDimensions,
    ua.AttributeIds.AccessLevel,
    ua.AttributeIds.UserAccessLevel,
    ua.AttributeIds.MinimumSamplingInterval,
    ua.AttributeIds.Historizing,
)
_METADATA_ATTR_NAMES: tuple[str, ...] = (
    "data_type_node_id",
    "value_rank",
    "array_dimensions",
    "access_level",
    "user_access_level",
    "minimum_sampling_interval",
    "historizing",
)


def _build_metadata_read_items(var_nodes: list[ua.NodeId]) -> list[ua.ReadValueId]:
    """One ReadValueId per (variable x attribute) pair, ordered (var-major,
    attr-minor) to match `_decode_metadata_results`."""
    return [
        ua.ReadValueId(NodeId_=v, AttributeId=attr) for v in var_nodes for attr in _METADATA_ATTRS
    ]


def _decode_metadata_results(
    items: list[ua.ReadValueId], results: list[ua.DataValue]
) -> dict[str, dict[str, Any]]:
    """Group results back per variable, keyed by NodeId.to_string().

    ``BadAttributeIdInvalid`` (and any other Bad status) becomes None for
    that field. ``data_type_node_id`` is stringified to canonical OPC UA
    form; ``array_dimensions`` becomes a tuple (or None when the server
    returns an empty list, which is what scalars produce).
    """
    n = len(_METADATA_ATTRS)
    out: dict[str, dict[str, Any]] = {}
    for v_idx in range(0, len(items), n):
        var_node_id = items[v_idx].NodeId.to_string()
        per_var: dict[str, Any] = {}
        for attr_idx, attr_name in enumerate(_METADATA_ATTR_NAMES):
            dv = results[v_idx + attr_idx]
            sc = dv.StatusCode_ if hasattr(dv, "StatusCode_") else dv.StatusCode
            ok = sc.is_good() if hasattr(sc, "is_good") else (getattr(sc, "value", 0) == 0)
            if not ok or dv.Value is None:
                per_var[attr_name] = None
                continue
            val = dv.Value.Value
            if val is None:
                per_var[attr_name] = None
            elif attr_name == "data_type_node_id":
                per_var[attr_name] = val.to_string()
            elif attr_name == "array_dimensions":
                per_var[attr_name] = tuple(val) if val else None
            else:
                per_var[attr_name] = val
        out[var_node_id] = per_var
    return out


_MODE_BY_NAME: dict[str, ua.MessageSecurityMode] = {
    "None": ua.MessageSecurityMode.None_,
    "Sign": ua.MessageSecurityMode.Sign,
    "SignAndEncrypt": ua.MessageSecurityMode.SignAndEncrypt,
}


def _resolve_endpoint_and_trust(
    endpoints: list[Any], cfg: ConnectionConfig
) -> tuple[str, Path | None]:
    """Pick the endpoint matching channel.policy + channel.mode; for
    ChannelSigned, also resolve the server cert.

    When `channel.server_trust_list_dir` is set: SHA-256-match the discovered
    `ServerCertificate` against the directory, refuse-on-no-match.
    When omitted: the discovered cert IS the identity. We persist it to a
    per-connection cache directory (`<tempdir>/i3xua-trust/<connection>/`)
    on first sight and reuse it on reconnect; the path is what gets passed
    into `set_security_string`.

    Returns (ApplicationUri, resolved_server_cert_path | None).
    """
    channel = cfg.channel
    mode = _MODE_BY_NAME[channel.mode]
    match = pick_matching_endpoint(endpoints, policy=channel.policy, mode=mode)
    if match is None:
        raise RuntimeError(
            f"no endpoint on {cfg.endpoint!r} matches "
            f"policy={channel.policy!r} mode={channel.mode!r}"
        )
    if isinstance(channel, ChannelNone):
        return match.Server.ApplicationUri, None
    assert isinstance(channel, ChannelSigned)

    if channel.server_trust_list_dir is not None:
        resolved = resolve_server_cert(
            server_cert_der=match.ServerCertificate,
            trust_dir=channel.server_trust_list_dir,
        )
    else:
        resolved = _autotrust_server_cert(cfg.name, match.ServerCertificate)
        logger.info(
            "auto-trusted discovered server cert for %s (no server_trust_list_dir "
            "configured); cached at %s",
            cfg.name,
            resolved,
        )
    return match.Server.ApplicationUri, resolved


def _autotrust_server_cert(connection_name: str, server_cert_der: bytes) -> Path:
    """Persist the discovered ServerCertificate into a per-connection cache
    directory and return the file path.

    Used when `channel.server_trust_list_dir` is omitted — the cert returned
    during endpoint discovery is treated as the server's identity. Writes are
    idempotent: on subsequent connects the same file is overwritten with the
    same bytes.
    """
    cache_dir = Path(tempfile.gettempdir()) / "i3xua-trust" / connection_name
    cache_dir.mkdir(parents=True, exist_ok=True)
    out = cache_dir / "server.der"
    out.write_bytes(server_cert_der)
    return out


def _ua_node_id(node_id_str: str) -> ua.NodeId:
    return ua.NodeId.from_string(node_id_str)


_NC_FROM_INT: dict[int, NodeClass] = {
    1: NodeClass.Object,
    2: NodeClass.Variable,
    4: NodeClass.Method,
    8: NodeClass.ObjectType,
    16: NodeClass.VariableType,
    32: NodeClass.ReferenceType,
    64: NodeClass.DataType,
    128: NodeClass.View,
}


def _node_class_from_ua(value: Any) -> NodeClass:
    # read_attributes returns raw int; per-node read returns ua.NodeClass enum.
    if isinstance(value, int) and not hasattr(value, "name"):
        return _NC_FROM_INT.get(value, NodeClass.Object)
    try:
        name = value.name if hasattr(value, "name") else str(value)
    except Exception:
        name = "Object"
    try:
        return NodeClass(name)
    except ValueError:
        return NodeClass.Object


def _is_null_node_id(node_id: Any) -> bool:
    """asyncua returns NodeId(Identifier=0, NamespaceIndex=0) for unset
    TypeDefinition fields. Treat that as 'no type definition'."""
    try:
        return bool(node_id.Identifier == 0 and node_id.NamespaceIndex == 0)
    except AttributeError:
        return False


# Module-level alias used by the lifted helper methods (_follow_continuations, _retry_starved).
_BAD_NO_CP_STATUS = ua.StatusCodes.BadNoContinuationPoints

# ---------------------------------------------------------------- BrowseSource impl


@dataclass
class _BrowseCounters:
    """Per-browse-run counters for continuation-point health.

    Surfaced via `browse_metrics[connection]` at end of `_on_connected`.

    Note: `browse_initial_calls` is incremented once per `_batch_browse_*`
    invocation. `browse_children` bumps it twice per batch (once for the
    hier browse, once for the typedef browse). Use this as the denominator
    for `browse_initial_starved` rate calculations.
    """

    browse_initial_calls: int = 0
    browse_initial_starved: int = 0
    browse_initial_starved_recovered: int = 0
    browse_initial_starved_unrecoverable: int = 0
    browse_next_calls: int = 0
    browse_next_starved: int = 0
    browse_next_other_bad: int = 0
    browse_next_starvation_logs_emitted: int = 0  # capped log counter
    browse_children_parent_bad_status: int = 0

    def as_metrics(self) -> dict[str, int]:
        return {
            "browse_children_parent_bad_status": self.browse_children_parent_bad_status,
            "browse_initial_calls": self.browse_initial_calls,
            "browse_initial_starved": self.browse_initial_starved,
            "browse_initial_starved_recovered": self.browse_initial_starved_recovered,
            "browse_initial_starved_unrecoverable": self.browse_initial_starved_unrecoverable,
            "browse_next_calls": self.browse_next_calls,
            "browse_next_starved": self.browse_next_starved,
            "browse_next_other_bad": self.browse_next_other_bad,
            "subtrees_dropped_silently": (self.browse_next_starved + self.browse_next_other_bad),
        }


class _AsyncuaBrowseSource(BrowseSource):
    """Adapts a live `asyncua.Client` to the browse Protocol.

    Intentionally defensive: any asyncua error on a specific node returns
    `None` from `get_node_info`/`get_type_info` so the walk keeps going.
    """

    def __init__(self, client: UaClientLike) -> None:
        self._client: Any = client  # asyncua.Client at runtime
        self.counters: _BrowseCounters = _BrowseCounters()
        # Captured during _pre_connect from the chosen EndpointDescription;
        # surfaced to the browse layer for the wrapper-cast namespace.
        self.application_uri: str | None = None
        self.application_name: str | None = None

    async def get_namespace_array(self) -> list[str]:
        return list(await self._client.get_namespace_array())

    async def get_application_uri(self) -> str | None:
        return self.application_uri

    async def get_application_name(self) -> str | None:
        return self.application_name

    async def _follow_continuations(self, results: list[Any], source_descs: list[Any]) -> None:
        """Drain every ContinuationPoint via BrowseNext and append the
        trailing References onto the matching first-batch result.

        Servers with high fan-out folders return ~1000 refs per node plus
        a ContinuationPoint that must be followed to retrieve the rest.
        Without this, large namespaces are silently truncated.

        Counters: every BrowseNext result is counted; per-result
        StatusCode bumps ``browse_next_starved`` (BadNoContinuationPoints)
        or ``browse_next_other_bad`` (any other non-Good). The first 10
        starvations are logged at WARNING with the originating NodeId.
        ``source_descs`` is the BrowseDescription list whose indices align
        with ``results``; it differs between the hier and typedef paths.

        Wire-protocol detail: asyncua's ``browse_next`` expects a
        ``BrowseNextParameters`` struct, not a bare list of CPs. Passing a
        list silently corrupts the request encoding and leaves
        ``browse_next_calls=0`` in metrics.
        """
        pending: list[tuple[int, bytes]] = [
            (i, r.ContinuationPoint) for i, r in enumerate(results) if r.ContinuationPoint
        ]
        while pending:
            cps = [cp for _, cp in pending]
            bn_params = ua.BrowseNextParameters()
            bn_params.ContinuationPoints = cps
            bn_params.ReleaseContinuationPoints = False
            next_results = await self._client.uaclient.browse_next(bn_params)
            new_pending: list[tuple[int, bytes]] = []
            for (orig_idx, _old_cp), nr in zip(pending, next_results, strict=True):
                self.counters.browse_next_calls += 1
                status_value = nr.StatusCode.value if nr.StatusCode is not None else 0
                if status_value == int(_BAD_NO_CP_STATUS):
                    self.counters.browse_next_starved += 1
                    if self.counters.browse_next_starvation_logs_emitted < 10:
                        self.counters.browse_next_starvation_logs_emitted += 1
                        logger.warning(
                            "browse_next: BadNoContinuationPoints on node %s "
                            "(remaining children silently lost; counters captured)",
                            source_descs[orig_idx].NodeId.to_string(),
                        )
                elif not nr.StatusCode.is_good():
                    self.counters.browse_next_other_bad += 1
                results[orig_idx].References.extend(nr.References or [])
                if nr.ContinuationPoint:
                    new_pending.append((orig_idx, nr.ContinuationPoint))
            pending = new_pending

    async def _retry_starved(
        self, browse_params: Any, descs_list: list[Any], results: list[Any]
    ) -> None:
        """Re-issue browses for any result that came back
        BadNoContinuationPoints — servers truncate with that status when
        their session-level CP pool is exhausted. Each retry runs SOLO so
        the freed CP is guaranteed available, and the result slot is
        overwritten in place.
        """
        starved: list[int] = [
            i for i, r in enumerate(results) if r.StatusCode.value == int(_BAD_NO_CP_STATUS)
        ]
        self.counters.browse_initial_starved += len(starved)
        while starved:
            idx = starved.pop()
            solo_params = ua.BrowseParameters()
            solo_params.View.Timestamp = ua.get_win_epoch()
            solo_params.RequestedMaxReferencesPerNode = browse_params.RequestedMaxReferencesPerNode
            solo_params.NodesToBrowse = [descs_list[idx]]
            solo = await self._client.uaclient.browse(solo_params)
            await self._follow_continuations(solo, [descs_list[idx]])
            if solo and solo[0].StatusCode.value == int(_BAD_NO_CP_STATUS):
                # Server still can't issue a CP even for one node;
                # log and accept the partial result.
                self.counters.browse_initial_starved_unrecoverable += 1
                logger.warning(
                    "browse: BadNoContinuationPoints persists on %s "
                    "even with batch=1; partial result kept",
                    descs_list[idx].NodeId.to_string(),
                )
                continue
            if not solo:
                self.counters.browse_initial_starved_unrecoverable += 1
                logger.warning(
                    "browse: solo retry for %s returned empty result; treating as unrecoverable",
                    descs_list[idx].NodeId.to_string(),
                )
                continue
            self.counters.browse_initial_starved_recovered += 1
            results[idx] = solo[0]

    async def get_node_info(self, node_id: str) -> NodeInfo | None:
        try:
            node = self._client.get_node(_ua_node_id(node_id))

            # perf: pipeline all independent reads via asyncio.gather
            # so they share one SecureChannel round-trip window instead of
            # serializing 6 sequential request/response pairs per node.
            browse_name_f = node.read_browse_name()
            display_name_f = node.read_display_name()
            node_class_f = node.read_node_class()
            hier_refs_f = node.get_references(
                refs=ua.NodeId(33, 0),  # HierarchicalReferences
                direction=ua.BrowseDirection.Forward,
                includesubtypes=True,
            )
            type_def_refs_f = node.get_references(
                refs=ua.NodeId(40, 0),  # HasTypeDefinition
                direction=ua.BrowseDirection.Forward,
            )

            results = await asyncio.gather(
                browse_name_f,
                display_name_f,
                node_class_f,
                hier_refs_f,
                type_def_refs_f,
                return_exceptions=True,
            )

            # Unpack — any individual failure is tolerated.
            for r in results[:3]:
                if isinstance(r, BaseException):
                    return None
            browse_name: Any = results[0]
            display_name: Any = results[1]
            node_class: Any = results[2]
            hier_refs: Any = results[3] if not isinstance(results[3], BaseException) else []
            type_def_refs: Any = results[4] if not isinstance(results[4], BaseException) else []

            refs_out: list[tuple[str, str]] = [
                (ref.ReferenceTypeId.to_string(), ref.NodeId.to_string()) for ref in hier_refs
            ]

            type_def_id: str | None = None
            if type_def_refs:
                type_def_id = type_def_refs[0].NodeId.to_string()

            data_type: str | None = None
            if _node_class_from_ua(node_class) is NodeClass.Variable:
                try:
                    dt = await node.read_data_type()
                    data_type = dt.to_string()
                except Exception:
                    data_type = None

            namespace_index = _ua_node_id(node_id).NamespaceIndex
            ns_array = await self._client.get_namespace_array()
            namespace_uri = ns_array[namespace_index] if namespace_index < len(ns_array) else ""

            return NodeInfo(
                node_id=node_id,
                browse_name=str(browse_name.Name),
                display_name=str(display_name.Text),
                node_class=_node_class_from_ua(node_class),
                namespace_uri=namespace_uri,
                data_type_node_id=data_type,
                type_definition_node_id=type_def_id,
                parent_node_id=None,
                hierarchical_refs=tuple(refs_out),
                has_component_children=any(ref[0] in HAS_COMPONENT_REFS for ref in refs_out),
            )
        except Exception as exc:
            logger.debug("get_node_info(%s) failed: %s", node_id, exc)
            return None

    async def get_node_info_batch(self, node_ids: list[str]) -> list[NodeInfo | None]:
        """Used only for BFS roots (1-3 NodeIds, off the hot path).
        Wraps per-node get_node_info — optimization here is unnecessary."""
        return [await self.get_node_info(nid) for nid in node_ids]

    async def browse_children(self, parent_node_ids: list[str]) -> list[BrowsedChild]:
        """One batched Browse(HierarchicalReferences, ResultMask=All) for
        the given parents, drain CPs, recover starved, then one batched
        DataType read for any Variable children. Return flat list of
        BrowsedChild across all parents (interleaved by parent index)."""
        if not parent_node_ids:
            return []

        nodes = [self._client.get_node(_ua_node_id(nid)) for nid in parent_node_ids]
        descs: list[Any] = []
        for n in nodes:
            d = ua.BrowseDescription()
            d.NodeId = n.nodeid
            d.BrowseDirection = ua.BrowseDirection.Forward
            d.ReferenceTypeId = ua.NodeId(33, 0)  # HierarchicalReferences
            d.IncludeSubtypes = True
            d.NodeClassMask = 0
            d.ResultMask = ua.BrowseResultMask.All
            descs.append(d)

        params = ua.BrowseParameters()
        params.View.Timestamp = ua.get_win_epoch()
        params.RequestedMaxReferencesPerNode = 0  # server decides
        params.NodesToBrowse = descs

        self.counters.browse_initial_calls += 1
        try:
            results = await self._client.uaclient.browse(params)
        except Exception as exc:
            logger.warning(
                "browse_children: initial Browse failed (%d parents): %s",
                len(parent_node_ids),
                exc,
            )
            return []

        await self._follow_continuations(results, descs)
        await self._retry_starved(params, descs, results)

        ns_array = await self._client.get_namespace_array()

        children: list[BrowsedChild] = []
        variable_children: list[int] = []  # indices into `children`

        for parent_idx, result in enumerate(results):
            parent_nid = parent_node_ids[parent_idx]
            if not result.StatusCode.is_good():
                # Per-parent failure (e.g. BadNodeIdUnknown after retry).
                # Skip; walker treats this as "no children." Counter
                # surfaces the rate via /admin/state — same convention
                # as browse_initial_starved/browse_next_starved.
                self.counters.browse_children_parent_bad_status += 1
                continue
            for ref in result.References or []:
                child_nid = ref.NodeId.to_string()
                ns_idx = ref.NodeId.NamespaceIndex
                ns_uri = ns_array[ns_idx] if 0 <= ns_idx < len(ns_array) else ""
                nc = _node_class_from_ua(ref.NodeClass)
                type_def = (
                    ref.TypeDefinition.to_string()
                    if ref.TypeDefinition is not None and not _is_null_node_id(ref.TypeDefinition)
                    else None
                )
                browse_name = (
                    str(ref.BrowseName.Name)
                    if hasattr(ref.BrowseName, "Name")
                    else str(ref.BrowseName)
                )
                display_name = (
                    str(ref.DisplayName.Text)
                    if hasattr(ref.DisplayName, "Text")
                    else str(ref.DisplayName)
                )
                info = NodeInfo(
                    node_id=child_nid,
                    browse_name=browse_name,
                    display_name=display_name,
                    node_class=nc,
                    namespace_uri=ns_uri,
                    type_definition_node_id=type_def,
                    data_type_node_id=None,  # filled below for Variables
                    parent_node_id=parent_nid,
                    hierarchical_refs=(),  # not needed; walker uses parent linkage
                    has_component_children=False,  # finalized post-walk
                )
                idx = len(children)
                children.append(
                    BrowsedChild(
                        info=info,
                        parent_node_id=parent_nid,
                        parent_relationship=RELATIONSHIP_NAMES.get(
                            ref.ReferenceTypeId.to_string(), ""
                        ),
                    )
                )
                if nc is NodeClass.Variable:
                    variable_children.append(idx)

        if variable_children:
            # Single multi-attribute Read instead of N single-attr reads.
            # Seven attributes per Variable (DataType + six metadata fields).
            # Bad statuses on individual attributes become None on the
            # NodeInfo; a Read-call-level exception still degrades silently.
            var_node_ids = [_ua_node_id(children[i].info.node_id) for i in variable_children]
            items = _build_metadata_read_items(var_node_ids)
            try:
                results = await self._client.uaclient.read(ua.ReadParameters(NodesToRead=items))
            except Exception as exc:
                logger.debug(
                    "browse_children: metadata Read for %d Variable children failed: %s",
                    len(var_node_ids),
                    exc,
                )
                return children
            metadata_by_node = _decode_metadata_results(items, results)
            for idx, var_nid in zip(variable_children, var_node_ids, strict=True):
                attrs = metadata_by_node.get(var_nid.to_string(), {})
                old = children[idx]
                children[idx] = replace(
                    old,
                    info=replace(
                        old.info,
                        data_type_node_id=attrs.get("data_type_node_id"),
                        value_rank=attrs.get("value_rank"),
                        array_dimensions=attrs.get("array_dimensions"),
                        access_level=attrs.get("access_level"),
                        user_access_level=attrs.get("user_access_level"),
                        minimum_sampling_interval=attrs.get("minimum_sampling_interval"),
                        historizing=attrs.get("historizing"),
                    ),
                )

        return children

    async def get_type_info(self, node_id: str) -> TypeInfo | None:
        """Return a `TypeInfo` with REAL InstanceDeclarations.

        For each `HasComponent` / `HasProperty` child of the ObjectType, read
        its `ModellingRule` (`Mandatory` -> `is_optional=False`, `Optional` ->
        True; placeholders covered too), its DataType NodeId, and ValueRank.
        Children without a ModellingRule are skipped (they're helpers, not
        InstanceDeclarations).
        """
        try:
            node = self._client.get_node(_ua_node_id(node_id))
            display_name = await node.read_display_name()

            # Detect VariableType vs ObjectType to decide whether to read DataType.
            try:
                node_class = await node.read_node_class()
            except Exception:
                node_class = ua.NodeClass.ObjectType  # safe default

            data_type_node_id: str | None = None
            if node_class == ua.NodeClass.VariableType:
                try:
                    dt = await node.read_data_type()
                    data_type_node_id = dt.to_string()
                except Exception as exc:
                    logger.debug("read_data_type(%s) failed: %s", node_id, exc)

            subtype_refs = await node.get_references(
                refs=ua.NodeId(45, 0),  # HasSubtype
                direction=ua.BrowseDirection.Forward,
            )
            subtypes = tuple(ref.NodeId.to_string() for ref in subtype_refs)

            namespace_index = _ua_node_id(node_id).NamespaceIndex
            ns_array = await self._client.get_namespace_array()
            namespace_uri = ns_array[namespace_index] if namespace_index < len(ns_array) else ""

            child_refs = []
            for ref_type_id in (ua.NodeId(47, 0), ua.NodeId(46, 0)):  # HasComponent, HasProperty
                try:
                    refs = await node.get_references(
                        refs=ref_type_id, direction=ua.BrowseDirection.Forward
                    )
                    child_refs.extend(refs)
                except Exception as exc:
                    logger.debug(
                        "get_references(%s, %s) failed: %s",
                        node_id,
                        ref_type_id.to_string(),
                        exc,
                    )

            fields: list[InstanceDeclaration] = []
            seen: set[str] = set()
            for ref in child_refs:
                child_id = ref.NodeId.to_string()
                if child_id in seen:
                    continue
                seen.add(child_id)
                child = self._client.get_node(ref.NodeId)
                try:
                    modelling_rule = await self._read_modelling_rule(child)
                except Exception:
                    modelling_rule = None
                if modelling_rule is None:
                    continue
                try:
                    cbn = await child.read_browse_name()
                    cdt = await child.read_data_type()
                    crank = await self._read_value_rank_safe(child)
                except Exception as exc:
                    logger.debug("InstanceDeclaration read failed on %s: %s", child_id, exc)
                    continue
                fields.append(
                    InstanceDeclaration(
                        name=str(cbn.Name),
                        data_type_node_id=cdt.to_string(),
                        value_rank=crank,
                        is_optional=modelling_rule in {"Optional", "OptionalPlaceholder"},
                    )
                )

            return TypeInfo(
                node_id=node_id,
                display_name=str(display_name.Text),
                namespace_uri=namespace_uri,
                fields=tuple(fields),
                subtypes=subtypes,
                data_type_node_id=data_type_node_id,
            )
        except Exception as exc:
            logger.debug("get_type_info(%s) failed: %s", node_id, exc)
            return None

    @staticmethod
    async def _read_modelling_rule(child: Any) -> str | None:
        """Return the DisplayName of the ModellingRule target
        (`Mandatory` / `Optional` / `MandatoryPlaceholder` / `OptionalPlaceholder`),
        or None if the child has no `HasModellingRule` reference."""
        try:
            refs = await child.get_references(
                refs=ua.NodeId(37, 0),  # HasModellingRule
                direction=ua.BrowseDirection.Forward,
            )
        except Exception:
            return None
        if not refs:
            return None
        return str(refs[0].DisplayName.Text)

    @staticmethod
    async def _read_value_rank_safe(child: Any) -> int:
        try:
            rank = await child.read_attribute(ua.AttributeIds.ValueRank)
            return int(rank.Value.Value)
        except Exception:
            return -1


# ---------------------------------------------------------------- asyncua-generated type reflection


_PY_TYPE_FOR_BUILTIN: dict[str, type] = {
    "ns=0;i=1": bool,
    "ns=0;i=2": int,
    "ns=0;i=3": int,
    "ns=0;i=4": int,
    "ns=0;i=5": int,
    "ns=0;i=6": int,
    "ns=0;i=7": int,
    # 64-bit integers are JSON strings on the wire (Part 6), but the Pydantic
    # model accepts Python ints here; serialization handles the string form.
    "ns=0;i=8": int,
    "ns=0;i=9": int,
    "ns=0;i=10": float,
    "ns=0;i=11": float,
    "ns=0;i=12": str,
    "ns=0;i=13": str,  # DateTime -> ISO string
    "ns=0;i=14": str,  # Guid
    "ns=0;i=15": bytes,
    "ns=0;i=16": str,
}


def _py_type_for_datatype(node_id: str) -> type:
    return _PY_TYPE_FOR_BUILTIN.get(node_id, object)


def _build_pydantic_model(desc: TypeDescriptor) -> Any:
    """Create a real Pydantic model whose fields mirror the ObjectType schema
    properties. Each property maps to a `(type, default)` tuple so
    `.model_json_schema()` reflects the real structure.

    Field Python types are coarse (we default to `Any` for non-primitive and
    complex nested types) since the authoritative wire format is Part-6 JSON
    and the i3X `ObjectType.schema` JSON Schema is what consumers validate
    against. The Pydantic model is primarily an in-process type handle.
    """
    from pydantic import create_model

    properties = desc.json_schema.get("properties") or {}
    required = set(desc.json_schema.get("required") or [])
    field_defs: dict[str, tuple[Any, Any]] = {}
    for name, schema in properties.items():
        py_type: Any = _py_type_from_schema(schema)
        default: Any = ... if name in required else None
        field_defs[name] = (py_type, default)

    safe_name = _safe_model_name(desc.source_node_id)
    if not field_defs:
        return create_model(f"T_{safe_name}")
    # mypy struggles to reconcile `**dict[str, tuple]` with create_model's
    # **kwargs overload; cast the kwargs expansion so it type-checks cleanly.
    kwargs: dict[str, Any] = dict(field_defs)
    return create_model(f"T_{safe_name}", **kwargs)


def _py_type_from_schema(schema: dict[str, Any]) -> Any:
    t = schema.get("type")
    if t == "boolean":
        return bool
    if t == "integer":
        return int
    if t == "number":
        return float
    if t == "string":
        return str
    if t == "array":
        return list
    return Any


def _safe_model_name(node_id: str) -> str:
    # Pydantic model names must be valid Python identifiers; sanitize
    # common NodeId separators.
    return (
        node_id.replace(";", "_")
        .replace("=", "_")
        .replace("/", "_")
        .replace("!", "_")
        .replace(".", "_")
        .replace("-", "_")
    )


async def _walk_server_structure_types(
    client: Any,
    *,
    connection: str,
    default_namespace_uri: str,
) -> list[TypeDescriptor]:
    """walk the server's Structure DataType hierarchy and emit a
    `TypeDescriptor` per type by reading its `DataTypeDefinition` attribute.

    Covers the types asyncua's `load_data_type_definitions` couldn't generate
    (e.g. those referencing the abstract `Enumeration` / `Number` / `Integer`
    bases that asyncua's generator doesn't know). We never call `exec` on
    generated code — just attribute reads.
    """
    from collections import deque

    out: list[TypeDescriptor] = []
    seen: set[str] = set()
    # Start from the abstract Structure base (`ns=0;i=22`). HasSubtype
    # traversal collects every concrete Structure subtype.
    base = client.get_node(ua.NodeId(22, 0))
    queue: deque[Any] = deque([base])
    is_base = True
    while queue:
        node = queue.popleft()
        nid = node.nodeid.to_string()
        if nid in seen:
            continue
        seen.add(nid)
        try:
            subs = await node.get_references(
                refs=ua.NodeId(45, 0),  # HasSubtype
                direction=ua.BrowseDirection.Forward,
            )
            for s in subs:
                queue.append(client.get_node(s.NodeId))
        except Exception as exc:
            logger.debug("HasSubtype walk from %s failed: %s", nid, exc)

        if is_base:
            # Don't emit a TypeDescriptor for the abstract Structure base.
            is_base = False
            continue

        descriptor = await _read_structure_definition(
            client, node, connection=connection, default_namespace_uri=default_namespace_uri
        )
        if descriptor is not None:
            out.append(descriptor)
    return out


async def _read_structure_definition(
    client: Any,
    node: Any,
    *,
    connection: str,
    default_namespace_uri: str,
) -> TypeDescriptor | None:
    try:
        display_name = await node.read_display_name()
        dt_def_read = await node.read_attribute(ua.AttributeIds.DataTypeDefinition)
    except Exception as exc:
        logger.debug("DataTypeDefinition read failed for %s: %s", node.nodeid, exc)
        return None
    dt_def = dt_def_read.Value.Value
    fields_attr = getattr(dt_def, "Fields", None)
    if fields_attr is None:
        # Either an enum (has `Fields` of a different shape) or an abstract
        # type without a definition. Enum handling can come later; for now skip.
        return None

    fields: list[tuple[str, str, int, bool]] = []
    for f in fields_attr:
        try:
            fields.append(
                (str(f.Name), f.DataType.to_string(), int(f.ValueRank), bool(f.IsOptional))
            )
        except Exception:
            continue
    if not fields:
        return None

    # Resolve namespace URI for the DataType itself.
    nid = node.nodeid
    namespace_uri = default_namespace_uri
    try:
        ns_array = await client.get_namespace_array()
        if int(nid.NamespaceIndex) < len(ns_array):
            namespace_uri = ns_array[int(nid.NamespaceIndex)]
    except Exception:
        pass

    source_node_id = nid.to_string()
    structural_hash = type_structural_hash(source_node_id, fields)
    schema, unresolved = structure_to_json_schema_with_unresolved(fields)
    return TypeDescriptor(
        source_node_id=source_node_id,
        display_name=str(display_name.Text),
        namespace_uri=namespace_uri,
        connection=connection,
        structural_hash=structural_hash,
        json_schema=schema,
        unresolved_fields=unresolved,
    )


def _enumerate_generated_types(
    *, connection: str, default_namespace_uri: str
) -> list[TypeDescriptor]:
    """Walk the `ua` module for classes created by `load_data_type_definitions`.

    asyncua's generator stamps each class with:
     - `data_type`: `ua.NodeId` of the DataType.
     - `ua_types`: list of `(field_name, field_type_reference)` tuples.

    We use those two attributes to build a real `TypeDescriptor` with genuine
    fields + JSON Schema. Enums emit integer schemas; Structures emit object
    schemas whose `properties` mirror the Python dataclass fields.
    """
    out: list[TypeDescriptor] = []
    for name in dir(ua):
        if name.startswith("_"):
            continue
        cls = getattr(ua, name)
        if not isinstance(cls, type):
            continue
        data_type = getattr(cls, "data_type", None)
        ua_types = getattr(cls, "ua_types", None)
        if data_type is None or ua_types is None:
            continue

        fields_meta: list[tuple[str, str, int, bool]] = []
        for entry in ua_types:
            # asyncua encodes each entry as (field_name, type_reference). The
            # type_reference is usually a class (primitive) or a string NodeId.
            field_name: str = entry[0]
            ref: Any = entry[1]
            node_id_str = _coerce_to_node_id_str(ref)
            fields_meta.append((field_name, node_id_str, -1, False))

        source_node_id = (
            data_type.to_string() if hasattr(data_type, "to_string") else str(data_type)
        )
        structural_hash = type_structural_hash(source_node_id, fields_meta)
        json_schema, unresolved = structure_to_json_schema_with_unresolved(fields_meta)

        out.append(
            TypeDescriptor(
                source_node_id=source_node_id,
                display_name=name,
                namespace_uri=default_namespace_uri,
                connection=connection,
                structural_hash=structural_hash,
                json_schema=json_schema,
                unresolved_fields=unresolved,
            )
        )
    return out


def _coerce_to_node_id_str(ref: Any) -> str:
    """Best-effort: asyncua's `ua_types` entries are heterogeneous across
    generator versions. Handle `ua.NodeId`, raw strings, and bare Python types."""
    if hasattr(ref, "to_string"):
        return ref.to_string()  # type: ignore[no-any-return]
    if isinstance(ref, str) and ref.startswith("ns="):
        return ref
    # Map Python builtins back to the closest OPC UA builtin. Anything unknown
    # becomes a generic object placeholder (schema fallback kicks in).
    for nid, py_type in _PY_TYPE_FOR_BUILTIN.items():
        if ref is py_type:
            return nid
    return "ns=0;i=22"  # Structure base


# ---------------------------------------------------------------- ConnectionBinding


class _ConnectionBinding:
    """Owns one `AsyncuaConnection` on a worker thread loop plus its shared
    asyncua Subscription. All public entrypoints are coroutines and must be
    invoked via `ThreadPool.run_on(cfg.name, ...)`."""

    def __init__(
        self,
        cfg: ConnectionConfig,
        pool: ThreadPool,
        main_loop: asyncio.AbstractEventLoop,
        registries: _Registries,
    ) -> None:
        self.cfg = cfg
        self.pool = pool
        self.main_loop = main_loop
        self.registries = registries
        self.conn = AsyncuaConnection(
            cfg,
            # asyncua's Client defaults: timeout=4s, watchdog_intervall=1.0s.
            # 4s is too tight for tag-heavy servers handling batched
            # read_attributes(DataType) against ~50K Variable NodeIds at
            # once — slow servers need >5s to parse and respond, the
            # watchdog times out, asyncua tears down the SecureChannel
            # mid-browse, and the walker silently truncates. 60s request
            # timeout gives ample headroom; watchdog interval stays at 1s
            # so disconnects are still detected promptly.
            client_factory=lambda endpoint: _UriAwareClient(url=endpoint, timeout=60),
            load_enums=load_enums,
        )
        self.conn.on_connected = self._on_connected
        self.conn.on_disconnected = self._on_disconnected
        self.conn.on_pre_connect = self._pre_connect
        # auto-tier state: one asyncua Subscription per distinct
        # PublishingInterval; per-tier nodeId -> server-side MonitoredItem handle.
        self._subs_by_publish: dict[int, Any] = {}
        self._monitored: dict[int, dict[str, int]] = {}
        # Captured during _pre_connect from the chosen EndpointDescription;
        # used to compose the wrapper-cast i3X namespace URI for this connection.
        self._application_uri: str | None = None
        self._application_name: str | None = None
        # Two-way wire ↔ raw NodeId index, refreshed at apply_snapshot time
        # from BrowseResult.nodes. Routes pass wire-side IDs in (display
        # paths for opaque NodeIds); the binding converts to raw OPC UA
        # NodeIds before talking to asyncua, and converts back when
        # delivering samples so they match the registry's wire-keyed
        # elementIds.
        self._wire_by_raw: dict[str, str] = {}
        self._raw_by_wire: dict[str, str] = {}

    async def start(self) -> None:
        await self.conn.start()

    async def stop(self) -> None:
        await self.conn.stop()

    async def _pre_connect(self, client: UaClientLike) -> Path | None:
        """Discover endpoints, match against configured policy/mode, resolve
        server cert against the trust list, stash the ApplicationUri for
        CreateSessionRequest, capture ApplicationUri+ApplicationName for the
        wrapper-cast i3X namespace, and return the resolved server cert path
        so `_connect_once` can pass it into `_apply_channel`.
        """
        endpoints = await client.connect_and_get_server_endpoints()
        server_uri, resolved = _resolve_endpoint_and_trust(endpoints, self.cfg)
        client._override_server_uri = server_uri  # type: ignore[attr-defined]
        # Capture ApplicationUri/ApplicationName for the wrapper-cast i3X
        # namespace. We re-pick the matched endpoint so the values are
        # consistent with the SecureChannel we open.
        mode = _MODE_BY_NAME[self.cfg.channel.mode]
        match = pick_matching_endpoint(endpoints, policy=self.cfg.channel.policy, mode=mode)
        if match is not None:
            self._application_uri = match.Server.ApplicationUri or None
            app_name = match.Server.ApplicationName
            self._application_name = (
                getattr(app_name, "Text", None) if app_name is not None else None
            ) or None
        logger.info(
            "opcua endpoint discovered for %s: ApplicationUri=%s policy=%s mode=%s",
            self.cfg.name,
            server_uri,
            self.cfg.channel.policy,
            self.cfg.channel.mode,
        )
        return resolved

    async def _discover_max_parents_per_batch(self, client: UaClientLike) -> int:
        """Read the server's published browse-related capabilities and pick a
        safe batch size for `_browse_instances`.

        Standard NodeIds (OPC UA Part 5):
          - `Server.ServerCapabilities.MaxBrowseContinuationPoints` i=2735
            (UInt16) — max simultaneous CPs the server will hand out.
          - `Server.ServerCapabilities.OperationLimits.MaxNodesPerBrowse`
            i=11488 (UInt32) — max nodes per BrowseRequest.

        We size each batch as the smaller of the two (capped to a sane
        ceiling) so we never demand more concurrent CPs than the server
        can give us — exceeding it causes the server to truncate
        high-fan-out folders with ``BadNoContinuationPoints``.

        Either attribute may be missing or zero on older servers; in that
        case we fall back to `MAX_PARENTS_PER_BATCH_DEFAULT`.
        """
        from i3xua.adapters.asyncua.browse import MAX_PARENTS_PER_BATCH_DEFAULT

        async def _read_uint(node_id: ua.NodeId) -> int | None:
            try:
                value = await client.get_node(node_id).read_value()  # type: ignore[attr-defined]
                return int(value) if value is not None else None
            except Exception as exc:
                logger.debug("could not read %s on %s: %s", node_id, self.cfg.name, exc)
                return None

        max_cps = await _read_uint(ua.NodeId(2735, 0))
        max_browse = await _read_uint(ua.NodeId(11488, 0))

        candidates = [v for v in (max_cps, max_browse) if v and v > 0]
        if not candidates:
            chosen = MAX_PARENTS_PER_BATCH_DEFAULT
            logger.info(
                "browse limits not exposed by %s; using default max_parents_per_batch=%d",
                self.cfg.name,
                chosen,
            )
        else:
            # Cap at MAX_PARENTS_PER_BATCH_DEFAULT to keep per-RPC payloads sane
            # even if a server claims arbitrarily large limits.
            chosen = max(1, min(min(candidates), MAX_PARENTS_PER_BATCH_DEFAULT))
            logger.info(
                "browse limits for %s: MaxBrowseContinuationPoints=%s, "
                "MaxNodesPerBrowse=%s → max_parents_per_batch=%d",
                self.cfg.name,
                max_cps,
                max_browse,
                chosen,
            )
        return chosen

    async def _on_connected(self, client: UaClientLike) -> None:
        logger.info("opcua connected: %s", self.cfg.name)
        # Read the server's published browse limits BEFORE we start walking.
        # Picking too high a batch size triggers ``BadNoContinuationPoints``
        # on tag-heavy servers and silently drops high-fan-out folders.
        max_parents = await self._discover_max_parents_per_batch(client)
        # Run a browse, then ship the results to the main loop's registries.
        # Phase timings (seconds) are recorded to surface startup performance
        # via /admin/state — useful when comparing a Reference Server (~7k
        # nodes) against a real PLC/OPC server (varies wildly).
        started_at = datetime.now(UTC)
        t_total = time.monotonic()
        source = _AsyncuaBrowseSource(client)
        source.application_uri = self._application_uri
        source.application_name = self._application_name
        cfg = BrowseConfig(
            namespace_allowlist=tuple(self.cfg.namespace_allowlist)
            if self.cfg.namespace_allowlist
            else (),
            max_parents_per_batch=min(max_parents, self.cfg.max_parents_per_batch),
            max_children_per_batch=self.cfg.max_children_per_batch,
            browse_variable_properties=self.cfg.browse_variable_properties,
        )
        try:
            t_browse = time.monotonic()
            result = await browse(source, connection=self.cfg.name, cfg=cfg)
            browse_s = time.monotonic() - t_browse
        except Exception as exc:
            logger.exception("initial browse failed for %s: %s", self.cfg.name, exc)
            return

        # + reflect custom types two ways so we don't lose anything
        # asyncua's codegen couldn't handle.
        #
        # (a) `_enumerate_generated_types` walks `ua.__dict__` for classes
        # asyncua successfully produced via `load_data_type_definitions`.
        # (b) `_walk_server_structure_types` reads `DataTypeDefinition` directly
        # from every server Structure DataType node — no code-gen, just
        # attribute reads. This catches types (e.g. those referencing the
        # abstract `Enumeration` base) where asyncua's generator bailed.
        #
        # Duplicates across the two passes are coalesced by `structural_hash`
        # when the TypeRegistry reconciles, so we can safely union them.
        # browse() guarantees ns=0 is always first in result.namespaces
        # (UA_CORE_NAMESPACE_URI). default_ns is therefore the OPC UA core URI.
        default_ns = result.namespaces[0].uri if result.namespaces else ""

        t_types = time.monotonic()
        codegen_types = _enumerate_generated_types(
            connection=self.cfg.name, default_namespace_uri=default_ns
        )
        walked_types: list[TypeDescriptor] = []
        try:
            walked_types = await _walk_server_structure_types(
                client, connection=self.cfg.name, default_namespace_uri=default_ns
            )
        except Exception as exc:
            logger.warning(
                "server-side DataTypeDefinition walk failed for %s: %s "
                "(continuing with codegen types only)",
                self.cfg.name,
                exc,
            )
        types_s = time.monotonic() - t_types

        # Dedup by (connection, source_node_id) so codegen wins when both paths
        # surface the same type with identical fields.
        by_source: dict[str, TypeDescriptor] = {}
        for t in (*walked_types, *codegen_types):
            by_source[t.source_node_id] = t
        custom_types = list(by_source.values())

        # `custom_types` come from `_enumerate_generated_types` via
        # asyncua's `load_data_type_definitions` — a separate path from
        # `_browse_types`, so they don't get the `application_uri` stamp
        # that `browse()` applies. Stamp them here so all merged types
        # carry the wrapper-cast namespaceUri ingredient.
        from dataclasses import replace as _dc_replace

        if self._application_uri is not None:
            custom_types = [
                _dc_replace(t, application_uri=self._application_uri) for t in custom_types
            ]
        merged_types = tuple(result.types) + tuple(custom_types)
        enriched = result.__class__(
            namespaces=result.namespaces,
            types=merged_types,
            nodes=result.nodes,
        )

        namespaces = [
            NamespaceInfo(uri=n.uri, connection=self.cfg.name, display_name=n.display_name)
            for n in enriched.namespaces
        ]
        # Refresh the wire ↔ raw NodeId index for this connection. Used
        # by `read_values` (wire → raw) and `deliver_sample` (raw → wire).
        self._wire_by_raw = {n.node_id: (n.wire_node_id or n.node_id) for n in enriched.nodes}
        self._raw_by_wire = {wire: raw for raw, wire in self._wire_by_raw.items()}
        t_snapshot = time.monotonic()
        await self._ship_to_main(
            self.registries.apply_snapshot(
                self.cfg.name,
                namespaces,
                enriched,
                application_uri=self._application_uri,
            )
        )
        snapshot_s = time.monotonic() - t_snapshot
        total_s = time.monotonic() - t_total

        # Stash + emit. The metrics dict is shared with AppState.browse_metrics
        # so /admin/state and the andon UI can render the latest run.
        completed_at = datetime.now(UTC)
        metrics: dict[str, Any] = {
            "started_at": started_at.isoformat(),
            "completed_at": completed_at.isoformat(),
            "browse_s": round(browse_s, 3),
            "types_s": round(types_s, 3),
            "snapshot_s": round(snapshot_s, 3),
            "total_s": round(total_s, 3),
            "namespaces": len(namespaces),
            "types": len(enriched.types),
            "instances": len(enriched.nodes),
        }
        # Keys from as_metrics() must stay in sync with the log line below.
        metrics.update(source.counters.as_metrics())
        self.registries.browse_metrics[self.cfg.name] = metrics
        logger.info(
            "browse complete: %s — %d ns / %d types / %d instances "
            "in %.2fs (browse %.2fs, types %.2fs, snapshot %.2fs); "
            "browse_next_starved=%d (out of %d calls), "
            "browse_initial_starved=%d (recovered=%d, unrecoverable=%d)",
            self.cfg.name,
            metrics["namespaces"],
            metrics["types"],
            metrics["instances"],
            total_s,
            browse_s,
            types_s,
            snapshot_s,
            metrics["browse_next_starved"],
            metrics["browse_next_calls"],
            metrics["browse_initial_starved"],
            metrics["browse_initial_starved_recovered"],
            metrics["browse_initial_starved_unrecoverable"],
        )

        # restore i3X-requested subscriptions now that the registries
        # reflect the (possibly drifted) address space. SubscriptionManager is
        # the authoritative source for what clients want; our local
        # `_monitored` bookkeeping is cleared on disconnect and rebuilt here.
        wanted = await self._ship_to_main(self.registries.wanted_node_ids(self.cfg.name))
        if wanted:
            logger.info(
                "restoring %d monitored items on %s after (re)connect",
                len(wanted),
                self.cfg.name,
            )
            await self.add_monitored(
                list(wanted),
                publishing_ms=self.cfg.default_publishing_interval_ms,
                sampling_ms=self.cfg.default_sampling_interval_ms,
            )

    async def _on_disconnected(self, exc: Exception | None) -> None:
        """session dropped. Drop local subscription bookkeeping so the next
        `_on_connected` creates a fresh asyncua Subscription and re-subscribes
        every element still present in `SubscriptionManager.elements`."""
        _ = exc
        self._subs_by_publish.clear()
        self._monitored.clear()

    async def _ship_to_main(self, coro: Any) -> Any:
        future = asyncio.run_coroutine_threadsafe(coro, self.main_loop)
        return await asyncio.wrap_future(future)

    async def read_values(self, node_ids: list[str]) -> list[ValueSample]:
        # Inputs may be wire-side IDs (display paths for opaque NodeIds);
        # convert to raw OPC UA NodeIds before reading, and translate the
        # resulting samples back to wire-side elementIds.
        node_ids = [self._raw_by_wire.get(nid, nid) for nid in node_ids]
        client = self.conn.client
        samples: list[ValueSample] = []
        for nid in node_ids:
            wire_nid = self._wire_by_raw.get(nid, nid)
            try:
                node = client.get_node(_ua_node_id(nid))  # type: ignore[attr-defined]
                dv = await node.read_data_value()
                neutral = from_ua_data_value(dv)
                samples.append(
                    sample_from_ouajson_data_value(
                        connection=self.cfg.name, node_id=wire_nid, data_value=neutral
                    )
                )
            except Exception as exc:
                logger.debug("read_values(%s!%s) failed: %s", self.cfg.name, nid, exc)
                samples.append(
                    ValueSample(
                        element_id=ElementRef(self.cfg.name, wire_nid).as_id(),
                        value=None,
                        quality=Quality.Bad,
                        timestamp="",
                    )
                )
        return samples

    async def _ensure_subscription(self, publishing_ms: int) -> Any:
        """one asyncua Subscription per distinct PublishingInterval.

        Sampling interval is per-MonitoredItem (see `add_monitored`), so all
        items at a given publishing interval share the same Subscription.
        """
        sub = self._subs_by_publish.get(publishing_ms)
        if sub is not None:
            return sub
        handler = _Handler(self)
        sub = await self.conn.client.create_subscription(publishing_ms, handler)  # type: ignore[attr-defined]
        self._subs_by_publish[publishing_ms] = sub
        return sub

    async def add_monitored(
        self, node_ids: list[str], *, publishing_ms: int, sampling_ms: int
    ) -> None:
        """subscribe each NodeId at the requested (pub, samp) tier.

        A single NodeId may end up with MonitoredItems on multiple tiers if
        different i3X registers ask for different intervals — we track each
        (nid, pub) combination separately so independent unregisters tear
        down only their own item.

        Inputs are wire-side IDs (display paths for opaque NodeIds);
        translated to raw OPC UA NodeIds before the asyncua call.
        """
        node_ids = [self._raw_by_wire.get(nid, nid) for nid in node_ids]
        sub = await self._ensure_subscription(publishing_ms)
        # Already-monitored nodes at THIS publishing tier are skipped — their
        # MonitoredItem already exists. Different publishing tiers get distinct
        # MonitoredItems even for the same NodeId.
        existing_for_pub = self._monitored.get(publishing_ms, {})
        new_ids = [nid for nid in node_ids if nid not in existing_for_pub]
        if not new_ids:
            return
        nodes = [self.conn.client.get_node(_ua_node_id(nid)) for nid in new_ids]  # type: ignore[attr-defined]
        from asyncua import ua  # local import keeps adapter the only asyncua importer

        params = ua.MonitoringParameters()
        params.SamplingInterval = float(sampling_ms)
        handles = await sub.subscribe_data_change(
            nodes, queuesize=0, sampling_interval=float(sampling_ms)
        )
        if not isinstance(handles, list):
            handles = [handles]
        bucket = self._monitored.setdefault(publishing_ms, {})
        for nid, h in zip(new_ids, handles, strict=False):
            bucket[nid] = int(h) if isinstance(h, int) else 0
        _ = params  # asyncua's high-level API takes sampling_interval directly

    async def remove_monitored(self, node_ids: list[str], *, publishing_ms: int) -> None:
        # Inputs are wire-side IDs; translate to raw before unsubscribing.
        node_ids = [self._raw_by_wire.get(nid, nid) for nid in node_ids]
        sub = self._subs_by_publish.get(publishing_ms)
        if sub is None:
            return
        bucket = self._monitored.get(publishing_ms)
        if not bucket:
            return
        drop: list[int] = []
        for nid in node_ids:
            h = bucket.pop(nid, None)
            if h is not None:
                drop.append(h)
        if drop:
            try:
                await sub.unsubscribe(drop)
            except Exception as exc:
                logger.debug("unsubscribe failed: %s", exc)
        # If this tier is now empty, tear down the Subscription itself.
        if not bucket:
            self._monitored.pop(publishing_ms, None)
            try:
                await sub.delete()
            except Exception as exc:
                logger.debug("delete subscription tier %d failed: %s", publishing_ms, exc)
            self._subs_by_publish.pop(publishing_ms, None)

    async def deliver_sample(self, node_id: str, data_value: OUaDataValue) -> None:
        """Called from the asyncua handler thread (via _Handler). Forwards the
        encoded sample to the main-loop SubscriptionManager + HistoryStore.
        `node_id` from asyncua is RAW; we translate to wire form so the
        emitted `element_id` matches the registry's wire-keyed entries.
        """
        wire_nid = self._wire_by_raw.get(node_id, node_id)
        sample = sample_from_ouajson_data_value(
            connection=self.cfg.name, node_id=wire_nid, data_value=data_value
        )
        logger.debug(
            "deliver_sample: element_id=%s quality=%s", sample.element_id, sample.quality
        )
        try:
            await self._ship_to_main(self.registries.fan_out(sample))
        except Exception as exc:
            logger.exception("fan_out failed: %s", exc)


class _Handler:
    """asyncua Subscription handler. Lives on the connection thread; its
    `datachange_notification` method is called synchronously by asyncua."""

    def __init__(self, binding: _ConnectionBinding) -> None:
        self._binding = binding
        self._pending: set[asyncio.Task[None]] = set()

    def datachange_notification(self, node: Any, val: Any, data: DataChangeNotif) -> None:
        _ = val
        try:
            node_id_str = node.nodeid.to_string()
            logger.debug("datachange_notification: node=%s val=%r", node_id_str, val)
            dv = data.monitored_item.Value
            neutral = from_ua_data_value(dv)
            loop = asyncio.get_event_loop()
            task = loop.create_task(self._binding.deliver_sample(node_id_str, neutral))
            self._pending.add(task)
            task.add_done_callback(self._pending.discard)
        except Exception as exc:
            logger.exception("datachange_notification failed: %s", exc)

    def status_change_notification(self, status: Any) -> None:
        """asyncua calls this when the Subscription's server-side status changes
        (e.g. BadTimeout after session drop, or StatusChangeNotification from a
        server restart). Log it so it's visible; the actual recovery is driven
        by `connection_lost_callback` → reconnect loop → subscription restoration."""
        logger.warning(
            "subscription status changed on %s: %s (recovery handled by reconnect loop)",
            self._binding.cfg.name,
            status,
        )


# ---------------------------------------------------------------- Registries bundle


class _Registries:
    """Holds the three registries + subscription manager + history on the main
    loop. Methods are coroutines intended to be scheduled from worker threads
    via `run_coroutine_threadsafe`."""

    def __init__(
        self,
        *,
        namespaces: NamespaceRegistry,
        types: TypeRegistry,
        instances: InstanceRegistry,
        subscriptions: SubscriptionManager,
        history: HistoryStore,
        browse_metrics: dict[str, dict[str, Any]] | None = None,
    ) -> None:
        self.namespaces = namespaces
        self.types = types
        self.instances = instances
        self.subscriptions = subscriptions
        self.history = history
        # Per-connection browse-phase timings, populated on each successful
        # (re)connect. Surfaced via /admin/state so operators can see how
        # long initial browse takes against a given OPC UA server.
        self.browse_metrics: dict[str, dict[str, Any]] = (
            browse_metrics if browse_metrics is not None else {}
        )

    async def apply_snapshot(
        self,
        connection: str,
        namespace_infos: list[NamespaceInfo],
        browse_result: BrowseResult,
        *,
        application_uri: str | None = None,
    ) -> None:
        # Namespaces. Only reconcile entries owned by this connection; others
        # (e.g. from a second server) remain untouched.
        current = self.namespaces.snapshot()
        keep_other_conns = [ni for ni in current.values() if ni.connection != connection]
        await self.namespaces.reconcile(keep_other_conns + namespace_infos)

        # Types: rebuild entries for this connection only. No custom Pydantic
        # models yet — ship an identity placeholder so the registry wiring works.

        # TypeRegistry has no per-connection reconcile; we compose the desired
        # set by filtering the current view.
        all_types = list(self.types.by_hash().values())
        keep = [rt for rt in all_types if rt.descriptor.connection != connection]
        desired = list(browse_result.types)
        # Clear & rewrite atomically.
        self.types._by_hash = {}
        self.types._by_source = {}
        for rt in keep:
            self.types._by_hash[rt.descriptor.structural_hash] = rt
            self.types._by_source[
                ElementRef(rt.descriptor.connection, rt.descriptor.source_node_id).as_id()
            ] = rt.descriptor.structural_hash

        for desc in desired:
            self.types._by_hash[desc.structural_hash] = RegisteredType(
                descriptor=desc,
                model=_build_pydantic_model(desc),
            )
            self.types._by_source[ElementRef(desc.connection, desc.source_node_id).as_id()] = (
                desc.structural_hash
            )

        # / CESMII RFC §3.3: every i3X deployment MUST carry an
        # `UnknownType` placeholder so instances whose TypeDefinition couldn't
        # be resolved (typically Methods in OPC UA, or any node reached without
        # a HasTypeDefinition edge) still carry a valid `typeId`. We register
        # one per connection so the ObjectType shows up in `/objecttypes`
        # alongside real types.
        unknown = TypeDescriptor(
            source_node_id="UnknownType",
            display_name="UnknownType",
            namespace_uri="urn:cesmii:i3x:placeholder",
            connection=connection,
            structural_hash=f"unknown-type-{connection}",
            json_schema={
                "type": "object",
                "description": (
                    "CESMII RFC §3.3 placeholder for instances whose source "
                    "type could not be resolved during browse."
                ),
            },
            version=None,
            application_uri=application_uri,
        )
        self.types._by_hash[unknown.structural_hash] = RegisteredType(
            descriptor=unknown,
            model=_build_pydantic_model(unknown),
        )
        self.types._by_source[ElementRef(unknown.connection, unknown.source_node_id).as_id()] = (
            unknown.structural_hash
        )

        # Instances: same per-connection semantics.
        all_instances = list(self.instances.snapshot().values())
        retained = [n for n in all_instances if n.connection != connection]
        await self.instances.reconcile(retained + list(browse_result.nodes))

    async def fan_out(self, sample: ValueSample) -> None:
        await self.subscriptions.push(sample)
        await self.history.append(sample)

    async def wanted_node_ids(self, connection: str) -> list[str]:
        """return raw NodeIds (no connection prefix) that some live i3X
        subscription currently has registered for `connection`.

        `_ConnectionBinding._on_connected` uses this to restore server-side
        MonitoredItems after a reconnect without consulting the adapter's
        own bookkeeping (which was cleared on disconnect)."""
        out: set[str] = set()
        for sub_id in await self.subscriptions.list_ids():
            elements = await self.subscriptions.get_elements(sub_id)
            for eid in elements:
                try:
                    ref = ElementRef.parse(eid)
                except ValueError:
                    continue
                if ref.connection == connection:
                    out.add(ref.node_id)
        return sorted(out)


# ---------------------------------------------------------------- façade


class AsyncuaUpstreamDataSource:
    """Top-level `UpstreamDataSource` implementation backed by asyncua.

    Construction is two-step so it can be handed to `build_state()` before
    the state's registries exist: call `bind_registries(...)` once the state
    has been built, then `await start()`.
    """

    def __init__(self, config: AppConfig) -> None:
        self._config = config
        self._pool = ThreadPool()
        self._registries: _Registries | None = None
        self._bindings: dict[str, _ConnectionBinding] = {}
        self._started = False

    def bind_registries(
        self,
        *,
        namespaces: NamespaceRegistry,
        types: TypeRegistry,
        instances: InstanceRegistry,
        subscriptions: SubscriptionManager,
        history: HistoryStore,
        browse_metrics: dict[str, dict[str, Any]] | None = None,
    ) -> None:
        self._registries = _Registries(
            namespaces=namespaces,
            types=types,
            instances=instances,
            subscriptions=subscriptions,
            history=history,
            browse_metrics=browse_metrics,
        )

    async def start(self) -> None:
        if self._started:
            return
        if self._registries is None:
            raise RuntimeError("bind_registries() must be called before start()")
        main_loop = asyncio.get_running_loop()
        for cfg in self._config.connections:
            binding = _ConnectionBinding(cfg, self._pool, main_loop, self._registries)
            self._bindings[cfg.name] = binding
            await self._pool.run_on(cfg.name, binding.start)
        self._started = True

    async def stop(self) -> None:
        if not self._started:
            return
        for name, binding in list(self._bindings.items()):
            try:
                await self._pool.run_on(binding.cfg.name, binding.stop)
            except Exception as exc:
                logger.debug("stop() for %s failed: %s", name, exc)
        await self._pool.stop()
        self._started = False

    # ------------------------------------------------------------------ Port impl

    async def list_connections(self) -> list[ConnectionId]:
        return [ConnectionId(name) for name in self._bindings]

    async def browse(self, connection: ConnectionId) -> BrowseResult:
        # The registries are the source of truth after initial browse.
        # A fresh browse is triggered via /admin/refresh which re-runs `_on_connected`.
        raise NotImplementedError("use /admin/refresh to re-browse")

    async def read_values(
        self, connection: ConnectionId, node_ids: Iterable[str]
    ) -> list[ValueSample]:
        binding = self._bindings[connection.name]
        ids = list(node_ids)
        return await self._pool.run_on(binding.cfg.name, lambda: binding.read_values(ids))

    async def add_monitored_items(
        self,
        handle: SubscriptionHandle,
        node_ids: Iterable[str],
        *,
        publishing_ms: int | None = None,
        sampling_ms: int | None = None,
    ) -> None:
        """dispatch to the (publishing_ms) tier on the target connection.

        When intervals aren't given (which is the path the i3X register route
        takes today), the connection's `default_*_interval_ms` from config
        applies. A non-default tier is created on demand by `_ensure_subscription`.
        """
        binding = self._bindings[handle.connection]
        ids = list(node_ids)
        pub = publishing_ms or binding.cfg.default_publishing_interval_ms
        samp = sampling_ms or binding.cfg.default_sampling_interval_ms
        await self._pool.run_on(
            binding.cfg.name,
            lambda: binding.add_monitored(ids, publishing_ms=pub, sampling_ms=samp),
        )

    async def remove_monitored_items(
        self,
        handle: SubscriptionHandle,
        node_ids: Iterable[str],
        *,
        publishing_ms: int | None = None,
    ) -> None:
        binding = self._bindings[handle.connection]
        ids = list(node_ids)
        pub = publishing_ms or binding.cfg.default_publishing_interval_ms
        await self._pool.run_on(
            binding.cfg.name,
            lambda: binding.remove_monitored(ids, publishing_ms=pub),
        )

    def stream(self, handle: SubscriptionHandle) -> Any:
        # Streaming is funneled through the i3X SubscriptionManager; this
        # placeholder is only present because the Protocol requires it.
        _ = handle

        async def _empty() -> Any:
            # Empty async generator: looping over `[]` makes this a generator
            # without unreachable-yield warnings from static analyzers.
            for _ in ():  # pragma: no cover
                yield  # pragma: no cover

        return _empty()


__all__ = ["AsyncuaUpstreamDataSource"]
